
drop view IF EXISTS NCVDVIK_H2T_SUMM_PII_NA_USA_LMI_VW;
drop view IF EXISTS NSCVV99A_H2T_SUMM_NA_USA_LI_VW;
drop view IF EXISTS NSCVV99A_H2T_SUMM_EU_FRA_LI_VW;
drop view IF EXISTS NSCVV99A_H2T_SUMM_EU_DEU_LI_VW;
drop view IF EXISTS NSCVV99A_H2T_SUMM_EU_ITA_LI_VW;
drop view IF EXISTS NSCVV99A_H2T_SUMM_EU_ESP_LI_VW;
drop view IF EXISTS NSCVV99A_H2T_SUMM_EU_GBR_LI_VW;
drop view IF EXISTS NSCVV99A_H2T_SUMM_NA_CAN_LI_VW;
drop VIEW IF EXISTS NSCVV99A_H2T_SUMM_EU_REG_LI_VW;